version: '3'
services:
  react-ui:
    build:
      context: ./labs4
    ports:
      - "3000:3000"
    container_name: react-ui
    stdin_open: true
    volumes:
       - ./labs4:/usr/src/app/my-app
       - /usr/src/app/labs4/node_modules
    command: npm start